"""Writes docs/ENEMY_REVIEW.md: every enemy, its stats and moves, with rough damage numbers.

Usage: python3 tools/enemy_sheet.py
Damage shown is at tier 1 (bosses are not scaled): base dmg x (1 + move dmg) x enemy_dmg_mult.
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load(name):
	with open(os.path.join(ROOT, "data", name + ".json"), encoding="utf-8") as f:
		return json.load(f)


enemies = load("enemies")
skills = load("skills")
regions = load("regions")
quests = load("quests")
cfg = load("config")
mult = float(cfg.get("enemy_dmg_mult", 1.0))


def where():
	seen = {}
	def add(eid, place):
		seen.setdefault(eid, [])
		if place not in seen[eid]:
			seen[eid].append(place)
	def groups(obj):
		for k in ("fights", "elites", "cave_fights"):
			for g in obj.get(k, []):
				yield g.get("enemies", [])
		for k in ("boss", "crossing"):
			if isinstance(obj.get(k), dict):
				yield obj[k].get("enemies", [])
		if isinstance(obj.get("final"), list):
			yield obj["final"]
	for rid, r in regions.items():
		if not isinstance(r, dict):
			continue
		for g in groups(r):
			for e in g:
				add(e, r.get("name", rid))
		for n in r.get("fixed_map", []) if isinstance(r.get("fixed_map"), list) else []:
			for e in n.get("data", {}).get("enemies", []) if isinstance(n, dict) else []:
				add(e, r.get("name", rid))
	for tid, t in quests.get("templates", {}).items():
		for g in groups(t):
			for e in g:
				add(e, "Quests")
	for eid, e in enemies.items():
		if not isinstance(e, dict):
			continue
		for sid in e.get("skills", []):
			for fx in skills.get(sid, {}).get("self_effects", []):
				if fx.get("type") == "summon":
					add(fx["enemy"], "summoned by " + e["name"])
	return seen


def effect_text(fx):
	t = fx.get("type")
	ch = fx.get("chance")
	chance = " (%d%%)" % ch if ch is not None and ch < 100 else ""
	if t in ("bleed", "poison"):
		extra = " (%d if user poisoned)" % fx["amount_if_self_poisoned"] if "amount_if_self_poisoned" in fx else ""
		return "%s %d x%d rounds%s%s" % (t, fx.get("amount", 0), fx.get("rounds", 3), extra, chance)
	if t == "extend":
		return "existing poison/bleed/debuffs +%d round" % fx.get("rounds", 1)
	if t == "debuff":
		return "%s %+d for %d rounds%s" % (fx.get("stat"), fx.get("value", 0), fx.get("rounds", 2), chance)
	if t == "fatigue":
		a = fx.get("amount", 0)
		if isinstance(a, list):
			if a[1] <= 0:
				return "%d to %d fatigue (relief)%s" % (a[1], a[0], chance)
			if a[0] < 0:
				return "%d to %+d fatigue%s" % (a[0], a[1], chance)
			return "+%d-%d fatigue" % tuple(a)
		return "%+d fatigue%s" % (a, " (relief)" if a < 0 else "")
	if t == "money":
		return "+%d chips" % fx.get("amount", 0)
	if t == "heal_self":
		return "heals self %d HP" % fx.get("amount", 5)
	if t == "heal_self_pct":
		return "heals self %d%% max HP" % fx.get("value", 10)
	if t == "buff":
		return "%s %+d%s" % (fx.get("stat"), fx.get("value", 0), " (rest of fight, stacks)" if fx.get("rounds", 3) >= 99 else " for %d rounds" % fx.get("rounds", 3))
	if t == "buff_kin":
		return "other %s: %s for %d rounds" % (fx.get("kin", "kin"), ", ".join("%s %+d" % (m["stat"], m["value"]) for m in fx.get("mods", [])), fx.get("rounds", 2))
	if t == "move":
		return "user moves %s %d" % ("forward" if fx.get("amount", 1) > 0 else "back", abs(fx.get("amount", 1)))
	if t == "stun":
		return "stun%s" % chance
	if t in ("knockback", "pull"):
		return "%s %d%s" % (t, fx.get("amount", 1), chance)
	if t == "heal":
		m = float(cfg.get("heal_mult", 1.0))
		return "heals %d-%d HP" % (round(fx.get("min", 3) * m), round(fx.get("max", 6) * m))
	if t == "heal_pct":
		return "heals %d%% max HP" % fx.get("value", 10)
	if t == "guard":
		return "guards the ally for %d rounds" % fx.get("rounds", 2)
	if t == "taunt":
		return "taunt %d rounds" % fx.get("rounds", 2)
	if t == "cure":
		return "cures " + "/".join(fx.get("kinds", ["bleed", "poison"]))
	if t == "clear_mark":
		return "clears mark"
	if t == "clear_shaken":
		return "cures Shaken"
	if t == "random_buff":
		return "random boon for %d rounds" % fx.get("rounds", 3)
	if t == "light":
		return "lamplight %+d" % fx.get("amount", 10)
	if t == "mark":
		return "mark %d rounds" % fx.get("rounds", 2)
	if t == "summon":
		return "summons " + enemies.get(fx.get("enemy"), {}).get("name", fx.get("enemy"))
	return t


def ranks(r):
	return "".join(str(x) for x in r) if r else "-"


def main():
	loc = where()
	out = ["# Enemy review", "",
		"Generated by `tools/enemy_sheet.py` from `data/enemies.json` and `data/skills.json`.",
		"Damage is at tier 1: base x (1 + move modifier) x %.2f. Heroes at level 1 have roughly 17-28 HP." % mult,
		"Ranks: *from* is where the enemy must stand to use the move. *Hits* says how many heroes it strikes and in which ranks: \"one of 123\" is a single target chosen from ranks 1-3, \"ALL of 1234\" strikes every hero in those ranks at once. AI weight is how often it picks the move relative to its others.", ""]
	order = [k for k, v in enemies.items() if isinstance(v, dict)]
	for eid in order:
		e = enemies[eid]
		kind = "Boss" if e.get("boss") else ("Elite" if e.get("elite") else "Regular")
		title = e["name"] + (" - " + e["title"] if e.get("title") else "")
		out.append("## %s  (%s)" % (title, kind))
		out.append("")
		out.append("`%s` | HP **%d** | dodge %d | prot %d | speed %d | acc %+d | crit %d%% | dmg %d-%d | tags: %s" % (
			eid, e["hp"], e.get("dodge", 0), e.get("prot", 0), e.get("speed", 0), e.get("acc", 0), e.get("crit", 0),
			e["dmg"][0], e["dmg"][1], ", ".join(e.get("tags", []))))
		res = e.get("res", {})
		out.append("Resists: " + ", ".join("%s %d" % (k, v) for k, v in res.items()))
		out.append("Found in: " + (", ".join(loc.get(eid, [])) or "(nowhere yet)"))
		out.append("")
		out.append("| Move | From | Hits | Acc | Damage | Effects | AI |")
		out.append("|---|---|---|---|---|---|---|")
		for sid in e.get("skills", []):
			s = skills.get(sid, {})
			if s.get("target") == "self" or s.get("no_damage"):
				dmg = "-"
			else:
				m = 1.0 + float(s.get("dmg", 0.0))
				lo, hi = e["dmg"][0] * m * mult, e["dmg"][1] * m * mult
				if s.get("dmg_range"):
					lo, hi = s["dmg_range"]
				dmg = "%d-%d" % (max(1, round(lo)), max(1, round(hi)))
				if s.get("aoe"):
					dmg += " each"
				if s.get("random_hits"):
					dmg += " x%d hits" % s["random_hits"]
				if s.get("crit"):
					dmg += ", +%d%% crit" % s["crit"]
				if s.get("vs_marked"):
					dmg += ", +%d%% vs marked" % round(s["vs_marked"] * 100)
			fx = [effect_text(x) for x in s.get("effects", []) + s.get("self_effects", [])]
			if s.get("target") == "self":
				hits = "self"
			elif s.get("aoe"):
				hits = "ALL of " + ranks(s.get("target_ranks"))
			elif s.get("random_hits"):
				hits = "%d random in %s" % (s["random_hits"], ranks(s.get("target_ranks")))
			else:
				hits = "one of " + ranks(s.get("target_ranks"))
			ai = str(s.get("ai", {}).get("weight", 1))
			if s.get("ai", {}).get("pref"):
				ai += " (" + s["ai"]["pref"] + (", always" if s["ai"].get("pref_chance") == 100 else "") + ")"
			acc = str(s.get("acc", "-")) if s.get("target") != "self" else "-"
			out.append("| **%s**: %s | %s | %s | %s | %s | %s | %s |" % (s.get("name", sid), s.get("desc", ""), ranks(s.get("use_ranks")), hits, acc, dmg, "; ".join(fx) or "-", ai))
		out.append("")
		out.append("Notes: ")
		out.append("")
	path = os.path.join(ROOT, "docs", "ENEMY_REVIEW.md")
	with open(path, "w", encoding="utf-8") as f:
		f.write("\n".join(out))
	print("wrote", path, len(order), "enemies")


if __name__ == "__main__":
	main()
