"""Writes docs/HERO_REVIEW.md: every hero class, its stats and all of its moves.

Usage: python3 tools/hero_sheet.py
Numbers are at level 1 with starting gear and skill level 1: damage is class dmg x
hero_dmg_mult x (1 + move modifier); heals include heal_mult.
"""
import os
from enemy_sheet import ROOT, gr, load, effect_text, ranks

classes = load("classes")
skills = load("skills")
cfg = load("config")
mult = float(cfg.get("hero_dmg_mult", 1.0))


def hits_text(s):
	t = s.get("target", "enemy")
	if t == "self":
		return "self"
	if t == "party":
		return "whole party"
	who = "ally" if t == "ally" else ""
	r = ranks(s.get("target_ranks") or [1, 2, 3, 4])
	if s.get("aoe_groups"):
		return "ALL of " + " or ".join(ranks(g) for g in s["aoe_groups"])
	if s.get("aoe"):
		return "ALL of " + r + (" (allies)" if who else "")
	if s.get("random_hits"):
		return "%d random in %s" % (s["random_hits"], r)
	return ("one ally in " + r) if who else ("one of " + r)


def main():
	out = ["# Hero review", "",
		"Generated by `tools/hero_sheet.py` from `data/classes.json` and `data/skills.json`.",
		"Numbers are at level 1, starting weapon, skill level 1 (damage x %.2f hero multiplier; heals x %.2f)." % (mult, float(cfg.get("heal_mult", 1.0))),
		"Each skill level adds +%d accuracy, +%d%% damage, +%d%% effect chance, +%d%% healing (max level %d)." % (
			cfg.get("skill_level_acc", 4), cfg.get("skill_level_dmg_pct", 8), cfg.get("skill_level_effect", 6), cfg.get("skill_level_heal_pct", 15), cfg.get("max_skill_level", 4)),
		"*From* is where the hero must stand; *Hits* is who it reaches (\"one of 12\" = a single enemy in ranks 1-2, \"ALL of 12\" = every enemy there).",
		"Effect chances are before the target's resistance (chance - resist = real odds). A new hero knows the first two (stock) moves plus two random others (★ = stock);",
		"the rest are learned at a Drill Hall. Heroes equip 4 moves at a time. Skills, weapons and armor go up to level 5.", ""]
	for cid, c in classes.items():
		if not isinstance(c, dict):
			continue
		out.append("## %s  (%s)" % (c["name"], c.get("role", "")))
		out.append("")
		out.append(c.get("desc", ""))
		out.append("")
		lo, hi = max(1, gr(c["dmg"][0] * mult)), max(1, gr(c["dmg"][1] * mult))
		out.append("`%s` | HP **%d** | dodge %d | prot %d | speed %d | acc %+d | crit %d%% | dmg %d-%d | prefers ranks %s" % (
			cid, c["hp"], c.get("dodge", 0), c.get("prot", 0), c.get("speed", 0), c.get("acc", 0), c.get("crit", 0), lo, hi, ranks(c.get("ranks"))))
		out.append("Resists: " + ", ".join("%s %d" % (k, v) for k, v in c.get("res", {}).items()))
		out.append("")
		out.append("| Move | From | Hits | Acc | Damage | Effects |")
		out.append("|---|---|---|---|---|---|")
		eq = c.get("skills", [])[:2]
		for sid in c.get("skills", []) + ([c["mega"]] if c.get("mega") else []):
			s = skills.get(sid, {})
			hostile = s.get("target", "enemy") == "enemy"
			if not hostile or s.get("no_damage"):
				dmg = "-"
			else:
				m = 1.0 + float(s.get("dmg", 0.0))
				# As the game does it: the (rounded) range rolls, then the move modifier applies.
				if s.get("dmg_range"):
					dmg = "%d-%d" % (max(1, gr(s["dmg_range"][0] * mult)), max(1, gr(s["dmg_range"][1] * mult)))
				else:
					dmg = "%d-%d" % (max(1, gr(lo * m)), max(1, gr(hi * m)))
				if s.get("aoe"):
					dmg += " each"
				if s.get("random_hits"):
					dmg += " x%d hits" % s["random_hits"]
				if s.get("hits", 1) > 1:
					dmg += " x%d hits" % s["hits"]
				if s.get("crit"):
					dmg += ", %+d%% crit" % s["crit"]
				if s.get("vs_marked"):
					dmg += ", +%d%% vs marked" % round(s["vs_marked"] * 100)
				if s.get("ignore_prot_pct"):
					dmg += ", ignores %d%% prot" % s["ignore_prot_pct"]
				if s.get("self_poisoned_bonus"):
					dmg += ", +%d%% while user is poisoned" % round(s["self_poisoned_bonus"] * 100)
				if s.get("low_hp_bonus"):
					dmg += ", +%d%% when below half HP" % round(s["low_hp_bonus"] * 100)
				for tag, v in s.get("vs_tags", {}).items():
					per = s.get("vs_tags_per_level", {}).get(tag, 0)
					dmg += ", %+d%% vs %s%s" % (round(v * 100), tag, " (+%d%% a level)" % round(per * 100) if per else "")
				if s.get("gamble"):
					dmg += ", 50/50: double or quarter"
			fx = [effect_text(x) for x in s.get("effects", [])] + ["self: " + effect_text(x) for x in s.get("self_effects", [])] + ["on kill: " + effect_text(x) for x in s.get("on_kill", [])] + ["no kill: " + effect_text(x) for x in s.get("on_fail", [])]
			if "transfuse_pct" in s:
				fx.insert(0, "heals most wounded ally %d%% of damage dealt" % s["transfuse_pct"])
			if s.get("momentum"):
				fx.append("**momentum %+d**" % s["momentum"])
			if s.get("spend_momentum"):
				fx.insert(0, "**MEGA: needs a full Momentum gauge, spends it all**")
			acc = str(s.get("acc", "-")) if hostile else "-"
			name = ("★ " if sid in eq else "") + "**%s**: %s" % (s.get("name", sid), s.get("desc", "")) + (" *(once per fight)*" if s.get("once_per_fight") else "")
			out.append("| %s | %s | %s | %s | %s | %s |" % (name, ranks(s.get("use_ranks")), hits_text(s), acc, dmg, "; ".join(fx) or "-"))
		out.append("")
		out.append("Notes: ")
		out.append("")
	path = os.path.join(ROOT, "docs", "HERO_REVIEW.md")
	with open(path, "w", encoding="utf-8") as f:
		f.write("\n".join(out))
	print("wrote", path)


if __name__ == "__main__":
	main()
