"""Writes docs/HERO_REVIEW.md: every hero class, its stats and all of its moves.

Usage: python3 tools/hero_sheet.py
Numbers are at level 1 with starting gear and skill level 1: damage is class dmg x
hero_dmg_mult x (1 + move modifier); heals include heal_mult.
"""
import os
from enemy_sheet import ROOT, load, effect_text, ranks

classes = load("classes")
skills = load("skills")
cfg = load("config")
mult = float(cfg.get("hero_dmg_mult", 1.0))


def hits_text(s):
	t = s.get("target", "enemy")
	if t == "self":
		return "self"
	if t == "party":
		return "whole party"
	who = "ally" if t == "ally" else ""
	r = ranks(s.get("target_ranks") or [1, 2, 3, 4])
	if s.get("aoe"):
		return "ALL of " + r + (" (allies)" if who else "")
	if s.get("random_hits"):
		return "%d random in %s" % (s["random_hits"], r)
	return ("one ally in " + r) if who else ("one of " + r)


def main():
	out = ["# Hero review", "",
		"Generated by `tools/hero_sheet.py` from `data/classes.json` and `data/skills.json`.",
		"Numbers are at level 1, starting weapon, skill level 1 (damage x %.2f hero multiplier; heals x %.2f)." % (mult, float(cfg.get("heal_mult", 1.0))),
		"Each skill level adds +%d accuracy, +%d%% damage, +%d%% effect chance, +%d%% healing (max level %d)." % (
			cfg.get("skill_level_acc", 4), cfg.get("skill_level_dmg_pct", 8), cfg.get("skill_level_effect", 6), cfg.get("skill_level_heal_pct", 15), cfg.get("max_skill_level", 4)),
		"*From* is where the hero must stand; *Hits* is who it reaches (\"one of 12\" = a single enemy in ranks 1-2, \"ALL of 12\" = every enemy there).",
		"Effect chances are before the target's resistance (chance - resist = real odds). ★ = equipped on a new hero. Heroes equip 4 moves at a time.", ""]
	for cid, c in classes.items():
		if not isinstance(c, dict):
			continue
		out.append("## %s  (%s)" % (c["name"], c.get("role", "")))
		out.append("")
		out.append(c.get("desc", ""))
		out.append("")
		lo, hi = round(c["dmg"][0] * mult), round(c["dmg"][1] * mult)
		out.append("`%s` | HP **%d** | dodge %d | prot %d | speed %d | acc %+d | crit %d%% | dmg %d-%d | prefers ranks %s" % (
			cid, c["hp"], c.get("dodge", 0), c.get("prot", 0), c.get("speed", 0), c.get("acc", 0), c.get("crit", 0), lo, hi, ranks(c.get("ranks"))))
		out.append("Resists: " + ", ".join("%s %d" % (k, v) for k, v in c.get("res", {}).items()))
		out.append("")
		out.append("| Move | From | Hits | Acc | Damage | Effects |")
		out.append("|---|---|---|---|---|---|")
		eq = c.get("default_equipped", [])
		for sid in c.get("skills", []):
			s = skills.get(sid, {})
			hostile = s.get("target", "enemy") == "enemy"
			if not hostile or s.get("no_damage"):
				dmg = "-"
			else:
				m = 1.0 + float(s.get("dmg", 0.0))
				dmg = "%d-%d" % (max(1, round(c["dmg"][0] * mult * m)), max(1, round(c["dmg"][1] * mult * m)))
				if s.get("aoe"):
					dmg += " each"
				if s.get("random_hits"):
					dmg += " x%d hits" % s["random_hits"]
				if s.get("hits", 1) > 1:
					dmg += " x%d hits" % s["hits"]
				if s.get("crit"):
					dmg += ", %+d%% crit" % s["crit"]
				if s.get("vs_marked"):
					dmg += ", +%d%% vs marked" % round(s["vs_marked"] * 100)
				if s.get("low_hp_bonus"):
					dmg += ", +%d%% when below half HP" % round(s["low_hp_bonus"] * 100)
				for tag, v in s.get("vs_tags", {}).items():
					dmg += ", %+d%% vs %s" % (round(v * 100), tag)
				if s.get("gamble"):
					dmg += ", 50/50: double or quarter"
			fx = [effect_text(x) for x in s.get("effects", [])] + ["self: " + effect_text(x) for x in s.get("self_effects", [])]
			acc = str(s.get("acc", "-")) if hostile else "-"
			name = ("★ " if sid in eq else "") + "**%s**: %s" % (s.get("name", sid), s.get("desc", ""))
			out.append("| %s | %s | %s | %s | %s | %s |" % (name, ranks(s.get("use_ranks")), hits_text(s), acc, dmg, "; ".join(fx) or "-"))
		out.append("")
		out.append("Notes: ")
		out.append("")
	path = os.path.join(ROOT, "docs", "HERO_REVIEW.md")
	with open(path, "w", encoding="utf-8") as f:
		f.write("\n".join(out))
	print("wrote", path)


if __name__ == "__main__":
	main()
